Added .NET Framework 4.6.1 back to supported targets
josephmyers/liblcm pull request #3
Opened 2022-06-16 04:02 UTC by josephmyers

This provides consuming projects another option if the .NET Standard version is causing issues.

2022-06-30 10:18 UTC, ermshiperete requested changes
I didn't do a full review, but have a few comments:

Using StrongNameSigner seems like a good idea (I originally went down that route as well) - unfortunately it causes problems in the projects that use the liblcm nuget package: StructureMap comes in as a transitive dependency, but is unsigned. This means all projects using liblcm directly or indirectly would need to reference StrongNameSigner as well. And what's more serious is that StrongNameSigner generates a signing key on the fly, so every machine creates a slightly different signed assembly. And because the liblcm nuget package/assembly mentions the key in the StructureMap reference, it won't work on any other machine.

2022-06-30 10:18 UTC, ermshiperete commented on src/SIL.LCModel/Application/Impl/DomainDataByFlid.cs
> +		public DomainDataByFlid(ICmObjectRepository cmObjectRepository, IStTextRepository stTxtRepository,
I'm not too keen on having these c'tors public even though it doesn't change anything in regards to the binary.

The reason is that all or at least most of these classes are implementation details and never intended to be created from outside of liblcm. Changing the c'tor to public muddles this intention a bit.

2022-06-30 10:18 UTC, ermshiperete commented on src/SIL.LCModel/LcmCache.cs
> +		public LcmCache()
This can't be `public` - `LcmCache` isn't intended to be created directly, only through one of the `CreateCache...` methods.

2022-06-30 14:04 UTC, josephmyers commented
Thanks for the look -- it sounds like that's the problem Hasso was having. I reverted that change and will get back on this tomorrow

2022-07-01 04:04 UTC, josephmyers commented
In the interest of stabilizing this branch for potential integration testing, I can stop pushes here. It will block me on the structuremap.patched work, but at this point I've realized that that effort is high-risk

2022-07-20 05:08 UTC, closed without merging